// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeHjssGYHL3xdIVCaZ3xhDNzvs6wJS7Ws',
    appId: '1:949960688501:web:54dfedab38f50f6310493c',
    messagingSenderId: '949960688501',
    projectId: 'recongenietask',
    authDomain: 'recongenietask.firebaseapp.com',
    storageBucket: 'recongenietask.firebasestorage.app',
    measurementId: 'G-18E1W4CJYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk_0ZJ3XHtpV7-XPQdrj0zKxiuszA7hqE',
    appId: '1:949960688501:android:ca9862f452102faa10493c',
    messagingSenderId: '949960688501',
    projectId: 'recongenietask',
    storageBucket: 'recongenietask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdItas6QeoMoyyJI21TDaB9__gCBdrnk',
    appId: '1:949960688501:ios:882bc8ad53b2122f10493c',
    messagingSenderId: '949960688501',
    projectId: 'recongenietask',
    storageBucket: 'recongenietask.firebasestorage.app',
    iosBundleId: 'com.example.recogenieTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGdItas6QeoMoyyJI21TDaB9__gCBdrnk',
    appId: '1:949960688501:ios:882bc8ad53b2122f10493c',
    messagingSenderId: '949960688501',
    projectId: 'recongenietask',
    storageBucket: 'recongenietask.firebasestorage.app',
    iosBundleId: 'com.example.recogenieTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeHjssGYHL3xdIVCaZ3xhDNzvs6wJS7Ws',
    appId: '1:949960688501:web:b490db428eb2f22f10493c',
    messagingSenderId: '949960688501',
    projectId: 'recongenietask',
    authDomain: 'recongenietask.firebaseapp.com',
    storageBucket: 'recongenietask.firebasestorage.app',
    measurementId: 'G-4YQXKK64WV',
  );
}
